name: CoreFramework
version: '2.0-HORIZON'
main: io.rhythmknights.coreframework.CoreFramework
api-version: '1.13'
authors: [RhythmKnights]
description: Management framework for all CorePlugins maintained by the RhythmKnights team
loadbefore: [CoreCommands, CoreExceed, CoreFlags, CoreTags, CoreWidgets]
libraries:
  - net.kyori:adventure-api:4.21.0
  - net.kyori:adventure-text-minimessage:4.21.0
  - net.kyori:adventure-text-serializer-legacy:4.21.0
  - net.kyori:adventure-platform-bukkit:4.4.0